apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "miclusterkubernetes"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "miclusterkubernetes"
    spec:
      containers:
        - name: "miclusterkubernetes"
          image: "mycontainerfinx.azurecr.io/miclusterkubernetes"
          ports:
          - containerPort: 80